server:
  port: 8010
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dz_groupware
    username: root
    password: password
  jackson:
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: localhost # 로컬에서 테스트 할 때는 localhost로 사용
    port: 6379
  jwt:
    secret:
      key: abcasdfdsafadsadsfdasfdsafadsfadsfsadfdasfsda
    token:
      access-expiration-time: 6000    # 12시간
      refresh-expiration-time: 604800000   # 7일
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml

useHttps: false

cloud:
  aws:
    credentials:
      accessKey: AKIAUYIFBFKNLD3LQW7B
      secretKey: 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
    s3:
      bucket: dz-test-image
      dir: /*
    region:
      static: ap-northeast-2
    stack:
      auto: false
